name: Linux build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang]
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependency
        run: ./action-install-linux.sh

      - name: Build and test
        run: make test
